Cargo.lock update to resolve runtime issue -     thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String,     table::TableKeyValue>` uninitialized, which is invalid', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/mem/mod.rs:671:9